// On-demand ionicons registration via npm package.
// Each icon's SVG data is imported individually and registered with addIcons,
// so only used icons are bundled — no CDN, no runtime fetch.

import { addIcons } from 'ionicons'
import {
  add, addOutline,
  arrowBackOutline,
  arrowRedo, arrowUndo,
  chatbubblesOutline,
  chevronBack, chevronBackOutline,
  chevronDown, chevronDownOutline,
  chevronExpandOutline,
  chevronForward, chevronForwardOutline,
  chevronUp, chevronUpOutline,
  close, closeOutline,
  cloudUploadOutline,
  codeSlash,
  colorPaletteOutline,
  colorWandOutline,
  downloadOutline,
  duplicateOutline,
  ellipsisVertical,
  helpCircleOutline, helpOutline,
  languageOutline,
  menuOutline,
  musicalNoteOutline, musicalNotesOutline,
  openOutline,
  phonePortraitOutline,
  refreshOutline,
  searchOutline,
  settingsOutline,
  sparklesOutline,
  swapHorizontal,
  trashOutline,
  briefcaseOutline,
  brushOutline,
  calculatorOutline,
  chatboxOutline,
  createOutline,
  flashOutline,
  idCardOutline,
  imageOutline,
  personCircleOutline,
  repeatOutline,
  stopwatchOutline,
  moonOutline,
  sunnyOutline,
  playOutline,
  pauseOutline
} from 'ionicons/icons'

addIcons({
  add, addOutline,
  arrowBackOutline,
  arrowRedo, arrowUndo,
  chatbubblesOutline,
  chevronBack, chevronBackOutline,
  chevronDown, chevronDownOutline,
  chevronExpandOutline,
  chevronForward, chevronForwardOutline,
  chevronUp, chevronUpOutline,
  close, closeOutline,
  cloudUploadOutline,
  codeSlash,
  colorPaletteOutline,
  colorWandOutline,
  downloadOutline,
  duplicateOutline,
  ellipsisVertical,
  helpCircleOutline, helpOutline,
  languageOutline,
  menuOutline,
  musicalNoteOutline, musicalNotesOutline,
  openOutline,
  phonePortraitOutline,
  refreshOutline,
  searchOutline,
  settingsOutline,
  sparklesOutline,
  swapHorizontal,
  trashOutline,
  briefcaseOutline,
  brushOutline,
  calculatorOutline,
  chatboxOutline,
  createOutline,
  flashOutline,
  idCardOutline,
  imageOutline,
  personCircleOutline,
  repeatOutline,
  stopwatchOutline,
  moonOutline,
  sunnyOutline,
  playOutline,
  pauseOutline
})
